# Generated by Django 3.1.2 on 2020-11-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bets',
            field=models.ManyToManyField(help_text="A list of Indication IDs. You can't place two bets to the same category.", to='core.Indication'),
        ),
    ]
