# Generated by Django 3.1.2 on 2020-12-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201216_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists'}, max_length=254, unique=True),
        ),
    ]
