# Generated by Django 3.1.2 on 2020-12-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201218_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indication',
            name='annotation',
            field=models.TextField(),
        ),
    ]
