# Generated by Django 3.1.2 on 2020-10-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nominated',
            new_name='Nominee',
        ),
        migrations.AlterModelOptions(
            name='nominee',
            options={'verbose_name_plural': 'nominatedes'},
        ),
    ]
