# Generated by Django 3.1.2 on 2020-12-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201107_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bets',
            field=models.ManyToManyField(blank=True, help_text="A list of Indication IDs. You can't place two bets to the same category.", to='main.Indication'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='User profile picture', upload_to='profile_pictures/'),
        ),
    ]
