# Generated by Django 3.1.2 on 2020-10-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201030_0219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nominee',
            options={'verbose_name_plural': 'nominees'},
        ),
    ]
