# Generated by Django 3.1.2 on 2020-10-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201030_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='share_code',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
