# Generated by Django 3.1.2 on 2020-12-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201218_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominee',
            old_name='picture',
            new_name='picture_cover',
        ),
        migrations.AddField(
            model_name='nominee',
            name='picture_thumbnail',
            field=models.ImageField(default=None, upload_to='nominees/'),
            preserve_default=False,
        ),
    ]
