# Generated by Django 3.1.2 on 2020-10-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201030_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='share_code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
