# Generated by Django 3.1.2 on 2020-10-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indication',
            name='year',
            field=models.IntegerField(),
        ),
    ]
