# Generated by Django 3.1.2 on 2020-12-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201218_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
