# Generated by Django 3.1.2 on 2020-11-02 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='score',
        ),
    ]
