# Generated by Django 3.1.2 on 2020-12-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201218_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='annotation',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
